### ISSUE TITLE
编译后的Windows版本运行bug

### ISSUE THREAD

**Issue by faint-memory** [alwaystest18/cdnChecker#1]
![image](https://github.com/alwaystest18/cdnChecker/assets/48248485/1e118a8f-7cff-423c-a878-43d96d6ee463)

**Comment by alwaystest18** [comment]
这个不是bug，是因为你的resolvers文件有效的dns不足20个，dns太少会导致影响判断的准确性，可以使用项目中自带的resolvers文件执行

**Comment by foyaga** [comment]
> 这个不是bug，是因为你的resolvers文件有效的dns不足20个，dns太少会导致影响判断的准确性，可以使用项目中自带的resolvers文件执行

我也是这个问题，用的就是项目中自带的resolvers文件

**Comment by alwaystest18** [comment]
> > 这个不是bug，是因为你的resolvers文件有效的dns不足20个，dns太少会导致影响判断的准确性，可以使用项目中自带的resolvers文件执行
> 
> 我也是这个问题，用的就是项目中自带的resolvers文件

我在windows主机上未复现此问题，请做以下尝试：
1.执行报错截图，排除使用问题
2.找几个resolvers文件中的dns本地使用试下（解析public1.114dns.com域名，看看结果是否为114.114.114.114）能否正常使用，如果均不能使用的话看看报什么错误，发个截图
