### ISSUE TITLE
有的域名有明显有cdn跟cname但是检测出来是没有cdn

### ISSUE THREAD

**Issue by glockie029** [alwaystest18/cdnChecker#2]

**Comment by alwaystest18** [comment]
推测可能原因：程序当前cdn的判断逻辑是使用不用地区的dns服务器去解析域名，如果存在4个以上不同的ip段，则判断使用cdn，反之未使用cdn，所以使用的resovers直接关乎检测结果的准确性，比如一个国内的cdn，使用国外的dns服务器或者使用国内同一个地区的dns解析得到的结果很可能是4个ip段以内，比如解析结果都是同一个cdn节点的ip
解决办法：
1.如果是有明显cdn的cname，可以把cname加到cdn_cname里面，当然也欢迎反馈，我直接在项目的cdn列表中增加
2.如果没有使用项目自带的resolvers.txt文件，可以试一下更换resolvers.txt为项目自带的，当然你这个情况还是方法1效果更好

另外，如果cdn_name文件中包含了cdn对应的cname，程序仍没检测出来使用cdn，属于程序bug，欢迎反馈具体信息，我这边测试下

**Comment by glockie029** [comment]
好的，我先尝试加到cdn_cname里，后续再用一下，如果有问题再来反馈
