### ISSUE TITLE
Although there are many DNS servers, this error still occurs

### ISSUE THREAD

**Issue by maplessa** [alwaystest18/cdnChecker#4]
The number of valid resolvers is less than 20, please improve it: resolvers.txt

**Comment by alwaystest18** [comment]
程序判断dns是否可用是根据解析public1.114dns.com结果中是否包含114.114.114.114这个ip判断的，如果你的列表中有很多dns服务器，但是仍然出现此错误，很可能是这些dns服务器不满足使用要求，你可以尝试换一台服务器去测试，或者寻找更多可用的dns服务器，可以使用此项目找出更多可用的dns服务器https://github.com/alwaystest18/dnsVerifier

**Comment by alwaystest18** [comment]
因长时间没有后续反馈，关闭需求
