### ISSUE TITLE
runtime: failed to create new OS thread

### ISSUE THREAD

**Issue by Admin123456-check** [alwaystest18/cdnChecker#5]
域名数量比较多，偶尔会出现报错

**Comment by alwaystest18** [comment]
你好，能否贴一下报错的截图，另外回答下下面的问题
1.请问域名数量是多少
2.“偶尔”的频率是怎样的，比如：跑了三次出现两次
3.使用的是默认线程数还是单独设置了线程数，如果是，设置了多少线程？

**Comment by Admin123456-check** [comment]
运行只显示一行报错runtime: failed to create new OS thread，然后停止，今天没有截图
1.域名三万+
2.不经常出现，mac平台
3.默认线程

**Comment by alwaystest18** [comment]
麻烦再次出现的时候附带一下截图，因为这个属于未定义的错误，会有问题所在行的信息

**Comment by eurakadmin** [comment]
今天测试多次没有出现，后续出现再截图补充吧

**Comment by Admin123456-check** [comment]
今天测试几次都没有出现，后续出现再补充截图吧

**Comment by alwaystest18** [comment]
由于长期没有新的反馈，先关闭
