### ISSUE TITLE
多域名下运行无输出结果 及 -oc输出结果错误

### ISSUE THREAD

**Issue by winezer0** [alwaystest18/cdnChecker#6]

**Comment by winezer0** [comment]
cdnChecker_1.0.0_windows_amd64

cdnChecker.exe -df domains.txt  -cf cdn_cname -r resolvers.txt  -o NoCdnDomain.txt  -oc CdnDomain.txt  -od NoCdnDomainIP.txt -oi  NoCdnIP.txt 


一百多个域名没有输出结果
![image](https://github.com/alwaystest18/cdnChecker/assets/46115146/44bfe65a-9c00-435a-a1b2-ff18a4f825cd)

只截取前十个域名的时候 只显示出一个cdn域名

NoCdnDomainIP.txt
![image](https://github.com/alwaystest18/cdnChecker/assets/46115146/03af5db0-77f0-4332-becd-ba18bedb9bc9)

CdnDomain.txt
![image](https://github.com/alwaystest18/cdnChecker/assets/46115146/6ecc10b6-5c58-4d8e-9298-c6b111c88925)


  -o NoCdnDomain.txt  -oc CdnDomain.txt   还发现这两个输出的域名是一样的!!!

**Comment by alwaystest18** [comment]
可以ping几个域名看看是不是可以正常解析ip
对于无法获取解析ip的域名，程序会默认为域名无效过滤掉

**Comment by winezer0** [comment]
域名都是可以正常访问的

**Comment by alwaystest18** [comment]
https://github.com/alwaystest18/dnsVerifier
可以尝试结合这个项目筛选一下dns服务器，域名能否访问要看你的resolvers.txt文件里的dns是否可用

**Comment by winezer0** [comment]
CdnChecker>dnsVerifier.exe -r resolvers.txt
CdnChecker>cdnChecker.exe -df domains.txt  -cf cdn_cname -r vaildResolvers.txt -o NoCdnDomain.txt  -oc CdnDomain.txt  -od NoCdnDomainIP.txt -oi  NoCdnIP.txt

![image](https://github.com/alwaystest18/cdnChecker/assets/46115146/95dde5c5-4dff-4342-8fb4-8d862f25592c)

多次测试运行后无输出结果,  大佬 可以留个邮箱我发域名资产给你执行测试看看?

**Comment by alwaystest18** [comment]
问题应该就是你的网络环境不能正常使用自带的dns服务器，假设你当前的dns是114.114.114.114，那么你就只在resolvers.txt中写114的这一个dns，再观察就应该有结果了，只是这样就相当于只用到了cname的判断方式，影响结果准确率

**Comment by alwaystest18** [comment]
如果按我上面说的只保留114测试还是没有结果，可以把域名发我邮箱447142089@qq.com

**Comment by winezer0** [comment]
cdnChecker.exe -df domains.txt  -cf cdn_cname -r resolversLess.txt -o NoCdnDomain.txt  -oc CdnDomain .txt  -od NoCdnDomainIP.txt -oi  NoCdnIP.txt

The number of valid resolvers is less than 20, please improve it: resolversLess.txt

要求dns服务器数量超过 20

**Comment by alwaystest18** [comment]
最新版本已经改成提醒不退出了，下载最新版本试试

**Comment by winezer0** [comment]
需要重新编译吗

**Comment by winezer0** [comment]
重新下载测试了，还是都没有结果 

命令1：
cdnChecker.exe -df domains.txt  -cf cdn_cname -r resolversLess.txt -o NoCdnDomain.txt  -oc CdnDomain.txt  -od NoCdnDomainIP.txt -oi  NoCdnIP.txt 

命令2：
dnsVerifier.exe -r resolvers.txt
cdnChecker.exe -df domains.txt  -cf cdn_cname -r vaildResolvers.txt -o NoCdnDomain.txt  -oc CdnDomain.txt  -od NoCdnDomainIP.txt -oi  NoCdnIP.txt 


邮件已发送，请查收

**Comment by alwaystest18** [comment]
已复现问题，原因是没有兼容windows下的换行导致，把domains文件转为unix的换行就可以正常跑了，近期修复此问题

**Comment by winezer0** [comment]
好的，感谢

**Comment by alwaystest18** [comment]
已修复
