### ISSUE TITLE
integer divide by zero

### ISSUE THREAD

**Issue by zh0u9527** [alwaystest18/cdnChecker#7]
goroutine 2293 [running]:
github.com/projectdiscovery/retryabledns.(*Client).queryMultiple(0xc00120b000, {0xc0000ac000, 0xc}, {0xc000e99a16, 0x1, 0xc0003d6db0?}, {0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:278 +0x1292
github.com/projectdiscovery/retryabledns.(*Client).QueryMultiple(...)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:213
github.com/projectdiscovery/retryabledns.(*Client).Query(0x455720?, {0xc0000ac000?, 0xc00039fad0?}, 0xacdb?)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:149 +0x3d
github.com/projectdiscovery/dnsx/libs/dnsx.(*DNSX).QueryOne(...)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.3/libs/dnsx/dnsx.go:117
main.CdnCheck({0xc0000ac000, 0xc}, {0xc00058d500, 0x325, 0x350}, {0x0?, 0x0, 0x0}, 0xc000a18318)
        /home/runner/work/cdnChecker/cdnChecker/cdnChecker.go:159 +0x11b
created by main.main
        /home/runner/work/cdnChecker/cdnChecker/cdnChecker.go:279 +0x90a
panic: runtime error: integer divide by zero

goroutine 2301 [running]:
github.com/projectdiscovery/retryabledns.(*Client).queryMultiple(0xc00120b000, {0xc0000ac076, 0xe}, {0xc000c1fa16, 0x1, 0xc000bc65a0?}, {0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:278 +0x1292
github.com/projectdiscovery/retryabledns.(*Client).QueryMultiple(...)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:213
github.com/projectdiscovery/retryabledns.(*Client).Query(0x7d58eb49?, {0xc0000ac076?, 0x0?}, 0x65a0?)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:149 +0x3d
github.com/projectdiscovery/dnsx/libs/dnsx.(*DNSX).QueryOne(...)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.3/libs/dnsx/dnsx.go:117
main.CdnCheck({0xc0000ac076, 0xe}, {0xc00058d500, 0x325, 0x350}, {0x0?, 0x0, 0x0}, 0xc000a18318)
        /home/runner/work/cdnChecker/cdnChecker/cdnChecker.go:159 +0x11b
created by main.main
        /home/runner/work/cdnChecker/cdnChecker/cdnChecker.go:279 +0x90a

**Comment by alwaystest18** [comment]
你好，这个问题是否可以稳定复现？能否给出测试的文件以及运行参数

**Comment by zh0u9527** [comment]
cat domain.txt
www.baidu.com
www.qq.com
aurora.tencent.com

$ ./cdnChecker -df domain.txt -cf cdn_cname -r resolvers.txt  
The number of valid resolvers is less than 20, May affect the accuracy of the results
panic: runtime error: integer divide by zero

goroutine 1517 [running]:
github.com/projectdiscovery/retryabledns.(*Client).queryMultiple(0xc000e31600, {0xc000139519, 0x12}, {0xc000493a16, 0x1, 0x0?}, {0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:278 +0x1292
github.com/projectdiscovery/retryabledns.(*Client).QueryMultiple(...)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:213
github.com/projectdiscovery/retryabledns.(*Client).Query(0x0?, {0xc000139519?, 0xc000493a50?}, 0x36f9?)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:149 +0x3d
github.com/projectdiscovery/dnsx/libs/dnsx.(*DNSX).QueryOne(...)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.3/libs/dnsx/dnsx.go:117
main.CdnCheck({0xc000139519, 0x12}, {0xc000514000, 0x325, 0x350}, {0x0?, 0x0, 0x0}, 0xc00009fe60)
        /home/runner/work/cdnChecker/cdnChecker/cdnChecker.go:159 +0x11b
created by main.main
        /home/runner/work/cdnChecker/cdnChecker/cdnChecker.go:279 +0x90a
panic: runtime error: integer divide by zero

goroutine 1515 [running]:
github.com/projectdiscovery/retryabledns.(*Client).queryMultiple(0xc000e31600, {0xc000139500, 0xd}, {0xc000623a16, 0x1, 0x0?}, {0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:278 +0x1292
github.com/projectdiscovery/retryabledns.(*Client).QueryMultiple(...)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:213
github.com/projectdiscovery/retryabledns.(*Client).Query(0x0?, {0xc000139500?, 0xc000623a50?}, 0x36f9?)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.21/client.go:149 +0x3d
github.com/projectdiscovery/dnsx/libs/dnsx.(*DNSX).QueryOne(...)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.3/libs/dnsx/dnsx.go:117
main.CdnCheck({0xc000139500, 0xd}, {0xc000514000, 0x325, 0x350}, {0x0?, 0x0, 0x0}, 0xc00009fe60)
        /home/runner/work/cdnChecker/cdnChecker/cdnChecker.go:159 +0x11b
created by main.main
        /home/runner/work/cdnChecker/cdnChecker/cdnChecker.go:279 +0x90a

**Comment by zh0u9527** [comment]
也是奇怪，我重新下载了一个就可以了
